'use client';

import React, { useState } from 'react';
import { TextInputPanel } from '@/components/text-detection/TextInputPanel';
import { VerdictDisplay } from '@/components/text-detection/VerdictDisplay';
import { DetectionVerdict } from '@/components/types';

export default function TextDetectionPage() {
  const [verdict, setVerdict] = useState<DetectionVerdict | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleAnalyzeText = (text: string) => {
    setIsLoading(true);
    setVerdict(null);
    
    // Simulate backend API call (mocking the future inference endpoint)
    setTimeout(() => {
      // Mock logic: randomly decide if it's AI or Human to demonstrate the UI
      const isAI = Math.random() > 0.5;
      const dummyVerdict: DetectionVerdict = {
        isAI,
        confidence: 0.75 + (Math.random() * 0.24), // Random confidence between 75% and 99%
        label: isAI ? 'AI Generated' : 'Human Written',
      };
      
      setVerdict(dummyVerdict);
      setIsLoading(false);
    }, 2000);
  };

  return (
    <div className="max-w-6xl mx-auto py-12 px-4 sm:px-6 lg:px-8 min-h-screen">
      <div className="mb-10 text-center">
        <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight">Text Detection Module</h1>
        <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
          Paste your text below to analyze whether it was generated by an AI model or written by a human.
        </p>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-stretch">
        <div className="flex flex-col h-full min-h-[400px]">
          <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 flex-grow flex flex-col">
            <h2 className="text-xl font-bold text-gray-900 mb-6">Input Text</h2>
            <div className="flex-grow">
              <TextInputPanel onSubmit={handleAnalyzeText} isLoading={isLoading} />
            </div>
          </div>
        </div>
        <div className="flex flex-col h-full min-h-[400px]">
          <VerdictDisplay verdict={verdict} isLoading={isLoading} />
        </div>
      </div>
    </div>
  );
}
