'use client';

import React, { useState } from 'react';
import axios from 'axios';
import { TextInputPanel } from '@/components/text-detection/TextInputPanel';
import { VerdictDisplay } from '@/components/text-detection/VerdictDisplay';
import { DetectionVerdict } from '@/components/types';
import { detectText } from '@/lib/api';
import { FormAlert } from '@/components/ui/FormAlert';

export default function TextDetectionPage() {
  const [verdict, setVerdict] = useState<DetectionVerdict | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleAnalyzeText = async (text: string) => {
    setIsLoading(true);
    setVerdict(null);
    setError(null);

    try {
      const result = await detectText(text);
      setVerdict(result);
    } catch (err: unknown) {
      if (axios.isAxiosError(err)) {
        const statusCode = err.response?.status;
        const detail = err.response?.data?.detail;

        if (statusCode === 400) {
          setError(
            typeof detail === 'string'
              ? detail
              : 'Invalid text input. Please ensure you entered at least 10 words.'
          );
        } else if (statusCode === 503) {
          setError('Text detection service is currently unavailable. Please try again shortly.');
        } else {
          setError(
            typeof detail === 'string'
              ? detail
              : err.message || 'An error occurred while analyzing the text. Please try again.'
          );
        }
      } else {
        setError('An unexpected error occurred. Please try again.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto py-12 px-4 sm:px-6 lg:px-8 min-h-screen">
      <div className="mb-10 text-center">
        <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight">Text Detection Module</h1>
        <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
          Paste your text below to analyze whether it was generated by an AI model or written by a human.
        </p>
      </div>

      {error && (
        <div className="mb-8 max-w-3xl mx-auto">
          <FormAlert
            type="error"
            title="Analysis Failed"
            message={error}
            onDismiss={() => setError(null)}
          />
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-stretch">
        <div className="flex flex-col h-full min-h-[400px]">
          <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 flex-grow flex flex-col">
            <h2 className="text-xl font-bold text-gray-900 mb-6">Input Text</h2>
            <div className="flex-grow">
              <TextInputPanel onSubmit={handleAnalyzeText} isLoading={isLoading} />
            </div>
          </div>
        </div>
        <div className="flex flex-col h-full min-h-[400px]">
          <VerdictDisplay verdict={verdict} isLoading={isLoading} />
        </div>
      </div>
    </div>
  );
}
